/**
 * City of Mist Character Sheet — A4 Template
 * Composed from agnostic building blocks.
 *
 * City of Mist stores game data as embedded Items:
 * themes (mystery), tags (subtype), statuses (tier), clues (source)
 */

import {
  BASE_STYLES,
  background,
  footer,
  header,
  itemList,
  section,
} from '../blocks';
import { registerTemplate } from '../definitions';
import type { RenderElement, TemplateDefinition } from '../types';

/** Single text line bound to actor.system — for mythos/logos display */
function identity(binding: string, y: number, color: string): RenderElement[] {
  return [
    {
      type: 'text',
      x: 56,
      y,
      content: binding,
      style: { fontSize: 9, color },
    },
  ];
}

export const TEMPLATE_A4_CITY_OF_MIST: TemplateDefinition = {
  meta: {
    id: 'pdf-a4-city-of-mist',
    name: 'City of Mist Character Sheet',
    description: 'Rift and sleeper character sheet',
    systemId: 'city-of-mist',
    width: 210,
    height: 297,
    exports: ['pdf', 'png'],
  },
  styles: BASE_STYLES,
  layout: [
    ...background(210, 297, '#faf8f5'),
    ...header(210, {
      barHeight: 55,
      badge: 'City of Mist',
    }),
    // Mythos / Logos identities (system-specific, below name)
    ...identity('{{actor.system.mythos}}', 27, '#c4a35a'),
    ...identity('{{actor.system.logos}}', 36, '#8899aa'),

    ...itemList('THEMES', 62, {
      filter: '{{item.system.mystery}}',
      content: '{{item.name}} — {{item.system.mystery}}',
      maxItems: 4,
      fontSize: 8,
    }),

    ...itemList('POWER TAGS', 102, {
      filter: '{{item.system.subtype}}',
      maxItems: 16,
      width: 90,
    }),

    ...itemList('STATUSES', 102, {
      filter: '{{item.system.tier}}',
      maxItems: 8,
      x: 110,
      width: 90,
    }),

    ...itemList('CLUES', 195, {
      filter: '{{item.system.source}}',
      content: '{{item.name}}',
      maxItems: 10,
      fontSize: 8,
    }),

    ...section('DESCRIPTION', 250),
    {
      type: 'text',
      x: 10,
      y: 261,
      width: 190,
      content: '{{actor.system.description}}',
      style: { fontSize: 8, color: '#444444' },
    },

    ...footer('City of Mist — Generated by Sheet Magnet', 297),
  ],
};

registerTemplate(TEMPLATE_A4_CITY_OF_MIST);
