/**
 * Legend in the Mist Character Sheet — A4 Template
 * Composed from agnostic building blocks.
 *
 * LitM stores:
 * - Tags/statuses on actor.system.floatingTagsAndStatuses[]
 * - Themes as item type:"themebook" with powertags[]/weaknesstags[] arrays
 * - Fellowships on actor.system.fellowships[]
 */

import {
  BASE_STYLES,
  background,
  footer,
  header,
  itemList,
  section,
  statRow,
} from '../blocks';
import { registerTemplate } from '../definitions';
import type { TemplateDefinition } from '../types';

export const TEMPLATE_A4_LITM: TemplateDefinition = {
  meta: {
    id: 'pdf-a4-litm',
    name: 'Legend in the Mist Character Sheet',
    description: 'Rift character sheet for Legend in the Mist',
    systemId: 'mist-engine-fvtt',
    width: 210,
    height: 297,
    exports: ['pdf', 'png'],
  },
  styles: BASE_STYLES,
  layout: [
    ...background(210, 297, '#f9f6f0'),
    ...header(210, {
      barHeight: 50,
      subtitle1: '{{actor.system.shortDescription}}',
      badge: 'Legend in the Mist',
    }),

    // Promises counter
    ...statRow(
      [
        { label: 'PROMISES', binding: '{{actor.system.promises}}' },
        { label: 'NOTES', binding: '{{actor.system.notes}}' },
      ],
      58,
    ),

    // Themebooks — items of type "themebook"
    ...itemList('THEMES', 75, {
      filter: '{{item.system.quest}}',
      content: '{{item.name}} — {{item.system.quest}}',
      maxItems: 4,
      fontSize: 8,
    }),

    // Tags & Statuses — on actor.system.floatingTagsAndStatuses
    ...section('TAGS & STATUSES', 115),
    {
      type: 'repeat',
      x: 10,
      y: 126,
      bind: '{{actor.system.floatingTagsAndStatuses}}',
      direction: 'vertical',
      gap: 0.5,
      maxItems: 12,
      template: [
        {
          type: 'text',
          x: 0,
          y: 0,
          width: 190,
          height: 4,
          content: '{{item.name}}',
          style: { fontSize: 7, color: '#333333' },
        },
      ],
    },

    // Fellowships — on actor.system.fellowships
    ...section('FELLOWSHIPS', 195),
    {
      type: 'repeat',
      x: 10,
      y: 206,
      bind: '{{actor.system.fellowships}}',
      direction: 'vertical',
      gap: 1,
      maxItems: 6,
      template: [
        {
          type: 'text',
          x: 0,
          y: 0,
          width: 190,
          height: 5,
          content: '{{item.companion}} — {{item.relationshipTag}}',
          style: { fontSize: 8, color: '#1a1a2e' },
        },
      ],
    },

    // Description
    ...section('BIOGRAPHY', 235),
    {
      type: 'text',
      x: 10,
      y: 246,
      width: 190,
      content: '{{actor.system.biography}}',
      style: { fontSize: 8, color: '#444444' },
    },

    ...footer('Legend in the Mist — Generated by Sheet Magnet', 297),
  ],
};

registerTemplate(TEMPLATE_A4_LITM);
