/**
 * Realistic City of Mist character actor data
 * Based on Foundry VTT city-of-mist system (taragnor/city-of-mist)
 *
 * ARCHITECTURE: City of Mist stores almost ALL game data as embedded
 * Item documents in actor.items[], NOT as fields on actor.system.
 * Themes, tags, statuses, clues, juice are all items.
 * The actor.system is intentionally sparse (biography, buildup, aliases).
 *
 * Source: https://github.com/taragnor/city-of-mist/blob/master/src/city-of-mist/module/datamodel/actor-types.ts
 */

import type { ActorData } from '$lib/connectors/foundry';

export const CITY_OF_MIST_CHARACTER: ActorData = {
  id: 'mV8pRn3kW2xYfL5q',
  name: 'Detective Marlowe',
  type: 'character',
  img: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
  system: {
    // -- actor.system is sparse in City of Mist --
    locked: false,
    biography:
      '<p>A grizzled PI with one clouded eye and two ravens that follow him everywhere.</p>',
    description: 'He sees more than he lets on.',
    short_description: 'Noir PI with divine sight',
    gmnotes: '',
    crewThemes: [],
    version: '1',
    finalized: true,
    mythos: 'Odin, the All-Father',
    logos: 'Private Investigator',
    selectedTags: [],
    selectedMove: null,
    selectedMoveGroup: 'Core',
    age: 42,
    residence: 'The Old Neighborhood',
    pronouns: 'he/him',
    alias: '?????',
    useAlias: true,
    essence: {
      systemName: '',
      isBurned: false,
    },
    activeExtraId: null,
    activeCrewId: null,
    buildup: [1, 1, 1, 0, 0],
    unspentBU: 0,
    flashback_used: false,
  },
  items: [
    // ── THEME 1: Mythos — Eye of Odin ────────────────────────────────
    {
      _id: 'theme001',
      name: 'Eye of Odin',
      type: 'theme',
      system: {
        description: '',
        locked: false,
        version: '1',
        tags: ['pt001', 'pt002', 'pt003', 'pt004', 'wt001'],
        improvements: {},
        attention: [1, 1, 0],
        crack: [0, 0, 0],
        milestone: [0, 0, 0],
        mystery: 'Why can I see the threads of fate?',
        subtype: 'Mythos',
        themebook_id: 'tb_divination',
        themebook_name: 'Divination',
        unspent_upgrades: 0,
        img: '',
        nascent: false,
        isExtra: false,
      },
    },
    // Power tags for Eye of Odin
    {
      _id: 'pt001',
      name: 'Visions of the future',
      type: 'tag',
      system: {
        description: '',
        locked: false,
        version: '1',
        question: '',
        question_letter: 'A',
        subtype: 'power',
        category: 'none',
        burn_state: 0,
        burned: false,
        crispy: false,
        is_bonus: false,
        theme_id: 'theme001',
        custom_tag: false,
        broad: false,
        temporary: false,
        permanent: false,
        parentId: null,
        subtagRequired: false,
        showcased: false,
      },
    },
    {
      _id: 'pt002',
      name: 'Read the runes',
      type: 'tag',
      system: {
        description: '',
        locked: false,
        version: '1',
        question: '',
        question_letter: 'B',
        subtype: 'power',
        category: 'none',
        burn_state: 0,
        burned: false,
        crispy: false,
        is_bonus: false,
        theme_id: 'theme001',
        custom_tag: false,
        broad: false,
        temporary: false,
        permanent: false,
        parentId: null,
        subtagRequired: false,
        showcased: false,
      },
    },
    {
      _id: 'pt003',
      name: 'See through illusions',
      type: 'tag',
      system: {
        description: '',
        locked: false,
        version: '1',
        question: '',
        question_letter: 'C',
        subtype: 'power',
        category: 'none',
        burn_state: 0,
        burned: false,
        crispy: false,
        is_bonus: false,
        theme_id: 'theme001',
        custom_tag: false,
        broad: false,
        temporary: false,
        permanent: false,
        parentId: null,
        subtagRequired: false,
        showcased: false,
      },
    },
    {
      _id: 'pt004',
      name: 'Wisdom of ages',
      type: 'tag',
      system: {
        description: '',
        locked: false,
        version: '1',
        question: '',
        question_letter: 'D',
        subtype: 'power',
        category: 'none',
        burn_state: 1,
        burned: true,
        crispy: false,
        is_bonus: false,
        theme_id: 'theme001',
        custom_tag: false,
        broad: false,
        temporary: false,
        permanent: false,
        parentId: null,
        subtagRequired: false,
        showcased: false,
      },
    },
    // Weakness tag for Eye of Odin
    {
      _id: 'wt001',
      name: 'Blind in one eye',
      type: 'tag',
      system: {
        description: '',
        locked: false,
        version: '1',
        question: '',
        question_letter: 'A',
        subtype: 'weakness',
        category: 'none',
        burn_state: 0,
        burned: false,
        crispy: false,
        is_bonus: false,
        theme_id: 'theme001',
        custom_tag: false,
        broad: false,
        temporary: false,
        permanent: false,
        parentId: null,
        subtagRequired: false,
        showcased: false,
      },
    },
    // ── THEME 2: Mythos — The Ravens ─────────────────────────────────
    {
      _id: 'theme002',
      name: 'The Ravens',
      type: 'theme',
      system: {
        description: '',
        locked: false,
        version: '1',
        tags: ['pt005', 'pt006', 'pt007', 'wt002'],
        improvements: {},
        attention: [1, 0, 0],
        crack: [0, 0, 0],
        milestone: [0, 0, 0],
        mystery: 'What do Huginn and Muninn whisper to me?',
        subtype: 'Mythos',
        themebook_id: 'tb_familiar',
        themebook_name: 'Familiar',
        unspent_upgrades: 0,
        img: '',
        nascent: false,
        isExtra: false,
      },
    },
    {
      _id: 'pt005',
      name: 'Huginn scouts ahead',
      type: 'tag',
      system: {
        description: '',
        locked: false,
        version: '1',
        question: '',
        question_letter: 'A',
        subtype: 'power',
        category: 'none',
        burn_state: 0,
        burned: false,
        crispy: false,
        is_bonus: false,
        theme_id: 'theme002',
        custom_tag: false,
        broad: false,
        temporary: false,
        permanent: false,
        parentId: null,
        subtagRequired: false,
        showcased: false,
      },
    },
    {
      _id: 'pt006',
      name: 'Muninn recalls everything',
      type: 'tag',
      system: {
        description: '',
        locked: false,
        version: '1',
        question: '',
        question_letter: 'B',
        subtype: 'power',
        category: 'none',
        burn_state: 0,
        burned: false,
        crispy: false,
        is_bonus: false,
        theme_id: 'theme002',
        custom_tag: false,
        broad: false,
        temporary: false,
        permanent: false,
        parentId: null,
        subtagRequired: false,
        showcased: false,
      },
    },
    {
      _id: 'wt002',
      name: 'Conspicuous birds',
      type: 'tag',
      system: {
        description: '',
        locked: false,
        version: '1',
        question: '',
        question_letter: 'A',
        subtype: 'weakness',
        category: 'none',
        burn_state: 0,
        burned: false,
        crispy: false,
        is_bonus: false,
        theme_id: 'theme002',
        custom_tag: false,
        broad: false,
        temporary: false,
        permanent: false,
        parentId: null,
        subtagRequired: false,
        showcased: false,
      },
    },
    // ── THEME 3: Logos — Gumshoe for Hire ────────────────────────────
    {
      _id: 'theme003',
      name: 'Gumshoe for Hire',
      type: 'theme',
      system: {
        description: '',
        locked: false,
        version: '1',
        tags: ['pt008', 'pt009', 'pt010', 'wt003'],
        improvements: {},
        attention: [0, 0, 0],
        crack: [1, 0, 0],
        milestone: [0, 0, 0],
        mystery: 'I solve cases others have given up on.',
        subtype: 'Logos',
        themebook_id: 'tb_routine',
        themebook_name: 'Routine',
        unspent_upgrades: 0,
        img: '',
        nascent: false,
        isExtra: false,
      },
    },
    {
      _id: 'pt008',
      name: 'Read people like a book',
      type: 'tag',
      system: {
        description: '',
        locked: false,
        version: '1',
        question: '',
        question_letter: 'A',
        subtype: 'power',
        category: 'none',
        burn_state: 0,
        burned: false,
        crispy: false,
        is_bonus: false,
        theme_id: 'theme003',
        custom_tag: false,
        broad: false,
        temporary: false,
        permanent: false,
        parentId: null,
        subtagRequired: false,
        showcased: false,
      },
    },
    {
      _id: 'pt009',
      name: 'Follow the clues',
      type: 'tag',
      system: {
        description: '',
        locked: false,
        version: '1',
        question: '',
        question_letter: 'B',
        subtype: 'power',
        category: 'none',
        burn_state: 0,
        burned: false,
        crispy: false,
        is_bonus: false,
        theme_id: 'theme003',
        custom_tag: false,
        broad: false,
        temporary: false,
        permanent: false,
        parentId: null,
        subtagRequired: false,
        showcased: false,
      },
    },
    {
      _id: 'wt003',
      name: "Can't let a case go",
      type: 'tag',
      system: {
        description: '',
        locked: false,
        version: '1',
        question: '',
        question_letter: 'A',
        subtype: 'weakness',
        category: 'none',
        burn_state: 0,
        burned: false,
        crispy: false,
        is_bonus: false,
        theme_id: 'theme003',
        custom_tag: false,
        broad: false,
        temporary: false,
        permanent: false,
        parentId: null,
        subtagRequired: false,
        showcased: false,
      },
    },
    // ── THEME 4: Logos — The Old Neighborhood ────────────────────────
    {
      _id: 'theme004',
      name: 'The Old Neighborhood',
      type: 'theme',
      system: {
        description: '',
        locked: false,
        version: '1',
        tags: ['pt011', 'pt012', 'wt004'],
        improvements: {},
        attention: [0, 0, 0],
        crack: [0, 0, 0],
        milestone: [0, 0, 0],
        mystery: 'This city is my home and I protect it.',
        subtype: 'Logos',
        themebook_id: 'tb_possessions',
        themebook_name: 'Possessions',
        unspent_upgrades: 0,
        img: '',
        nascent: false,
        isExtra: false,
      },
    },
    {
      _id: 'pt011',
      name: 'Office above the diner',
      type: 'tag',
      system: {
        description: '',
        locked: false,
        version: '1',
        question: '',
        question_letter: 'A',
        subtype: 'power',
        category: 'none',
        burn_state: 0,
        burned: false,
        crispy: false,
        is_bonus: false,
        theme_id: 'theme004',
        custom_tag: false,
        broad: false,
        temporary: false,
        permanent: false,
        parentId: null,
        subtagRequired: false,
        showcased: false,
      },
    },
    {
      _id: 'pt012',
      name: 'Trusty revolver',
      type: 'tag',
      system: {
        description: '',
        locked: false,
        version: '1',
        question: '',
        question_letter: 'B',
        subtype: 'power',
        category: 'none',
        burn_state: 0,
        burned: false,
        crispy: false,
        is_bonus: false,
        theme_id: 'theme004',
        custom_tag: false,
        broad: false,
        temporary: false,
        permanent: false,
        parentId: null,
        subtagRequired: false,
        showcased: false,
      },
    },
    {
      _id: 'wt004',
      name: 'Behind on rent',
      type: 'tag',
      system: {
        description: '',
        locked: false,
        version: '1',
        question: '',
        question_letter: 'A',
        subtype: 'weakness',
        category: 'none',
        burn_state: 0,
        burned: false,
        crispy: false,
        is_bonus: false,
        theme_id: 'theme004',
        custom_tag: false,
        broad: false,
        temporary: false,
        permanent: false,
        parentId: null,
        subtagRequired: false,
        showcased: false,
      },
    },
    // ── STORY TAGS (type: "tag", subtype: "story") ───────────────────
    {
      _id: 'st001',
      name: 'Knows the streets',
      type: 'tag',
      system: {
        description: '',
        locked: false,
        version: '1',
        question: '',
        question_letter: '',
        subtype: 'story',
        category: 'none',
        burn_state: 0,
        burned: false,
        crispy: false,
        is_bonus: false,
        theme_id: '',
        custom_tag: false,
        broad: false,
        temporary: false,
        permanent: false,
        parentId: null,
        subtagRequired: false,
        showcased: false,
      },
    },
    {
      _id: 'st002',
      name: 'Owes a favor to Big Sal',
      type: 'tag',
      system: {
        description: '',
        locked: false,
        version: '1',
        question: '',
        question_letter: '',
        subtype: 'story',
        category: 'none',
        burn_state: 0,
        burned: false,
        crispy: false,
        is_bonus: false,
        theme_id: '',
        custom_tag: false,
        broad: false,
        temporary: false,
        permanent: false,
        parentId: null,
        subtagRequired: false,
        showcased: false,
      },
    },
    // ── STATUSES (type: "status") ────────────────────────────────────
    {
      _id: 'stat001',
      name: 'Tired-2',
      type: 'status',
      system: {
        description: '',
        locked: false,
        version: '1',
        tier: 2,
        pips: 0,
        category: 'none',
        hidden: false,
        spectrum_status: '',
        temporary: false,
        permanent: false,
        sceneId: null,
        showcased: false,
        specialType: '',
      },
    },
    {
      _id: 'stat002',
      name: 'Suspicious-1',
      type: 'status',
      system: {
        description: '',
        locked: false,
        version: '1',
        tier: 1,
        pips: 0,
        category: 'none',
        hidden: false,
        spectrum_status: '',
        temporary: false,
        permanent: false,
        sceneId: null,
        showcased: false,
        specialType: '',
      },
    },
    // ── CLUES (type: "clue") ─────────────────────────────────────────
    {
      _id: 'clue001',
      name: 'The warehouse fire was no accident',
      type: 'clue',
      system: {
        description: '',
        locked: false,
        version: '1',
        amount: 1,
        source: 'Scene investigation',
        method: 'Investigate',
        partial: false,
        metaSource: '',
        tagsUsed: ['pt001'],
      },
    },
    {
      _id: 'clue002',
      name: 'Someone inside the precinct is covering tracks',
      type: 'clue',
      system: {
        description: '',
        locked: false,
        version: '1',
        amount: 1,
        source: 'Police contact',
        method: 'Convince',
        partial: true,
        metaSource: '',
        tagsUsed: ['pt008'],
      },
    },
  ],
  effects: [],
  flags: {},
  prototypeToken: {
    name: 'Marlowe',
    displayName: 20,
    actorLink: true,
    width: 1,
    height: 1,
    texture: {
      src: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
    },
    disposition: 1,
  },
  _meta: {
    systemId: 'city-of-mist',
    systemVersion: '2.5.0',
    foundryVersion: '12.331',
    exportedAt: '2026-04-04T20:00:00.000Z',
  },
};
