export default {
  // ── Nav ────────────────────────────────────────────────────────────
  nav: {
    features: 'Features',
    faq: 'FAQ',
    contact: 'Contact',
  },

  // ── Landing page ───────────────────────────────────────────────────
  landing: {
    heroSubtitle:
      'Export your TTRPG character sheets to anything — PDF, images and more.',
    getStarted: 'Get Started',
    connectTitle: 'Connect to Foundry',
    connectHint:
      'Open Foundry VTT and click the Sheet Magnet button to get your connection details.',
    foundryUrl: 'Foundry URL',
    accessToken: 'Access Token',
    connect: 'Connect',
    connecting: 'Connecting…',
    orScanQR: 'Or scan QR code',
    scanQR: 'Scan QR Code',
    stopScan: 'Stop Scan',
    scanHint: 'Point your camera at the QR code shown in Foundry VTT.',
    connectionError: 'Connection failed. Check your URL and token.',
  },

  // ── Select characters ──────────────────────────────────────────────
  select: {
    title: 'Select Characters',
    noCharacters: 'No characters found in this world.',
    fetchError: 'Failed to load characters. Check your Foundry connection.',
    disconnect: 'Disconnect',
    continue: 'Continue',
  },

  // ── Template selection ─────────────────────────────────────────────
  template: {
    title: 'Choose Format',
    subtitle: 'Select an export format for your {count} character(s)',
    systemSpecific: 'System-specific',
    genericFormats: 'Generic formats',
    back: 'Back',
    preview: 'Preview',
  },

  // ── Preview ────────────────────────────────────────────────────────
  preview: {
    title: 'Preview',
    back: 'Back',
    export: 'Export',
    noData: 'No character data available',
  },

  // ── Export ──────────────────────────────────────────────────────────
  export: {
    title: 'Export',
    complete: 'Export Complete!',
    downloaded: 'Your character sheet(s) have been downloaded.',
    exportMore: 'Export More Characters',
    disconnect: 'Disconnect',
    download: 'Download',
    downloadPdf: 'Download PDF',
    downloadPng: 'Download PNG',
    generatingPdf: 'Generating PDF…',
    generatingPng: 'Generating PNG…',
    pdfDesc: 'Vector format, best for printing',
    pngDesc: 'Image format, best for sharing',
    printServices: 'Print Services',
    printHint: 'Order physical prints delivered to your door',
    printful: 'Printful',
    printfulDesc: 'Cards, posters, stickers & more',
    pencilWrap: 'Pencil Wrap',
    pencilWrapDesc: 'Your character on a pencil',
    soon: 'Soon',
    backToPreview: 'Back to Preview',
  },

  // ── PDF section headers ────────────────────────────────────────────
  pdf: {
    abilities: 'ABILITIES',
    abilityScores: 'ABILITY SCORES',
    combat: 'COMBAT',
    details: 'DETAILS',
    inventory: 'INVENTORY',
    inventoryFeatures: 'INVENTORY & FEATURES',
    items: 'ITEMS',
    themes: 'THEMES',
    powerTags: 'POWER TAGS',
    weaknessTags: 'WEAKNESS TAGS',
    statuses: 'STATUSES',
    clues: 'CLUES',
    description: 'DESCRIPTION',
    tagsStatuses: 'TAGS & STATUSES',
    fellowships: 'FELLOWSHIPS',
    biography: 'BIOGRAPHY',
    stats: 'STATS',
    resources: 'RESOURCES',
    playbookMoves: 'PLAYBOOK MOVES',
    basicMoves: 'BASIC MOVES',
    footer: 'Generated by Sheet Magnet',
    inspired: 'INSPIRED',
  },
};
