/**
 * Bootstrap a new Foundry VTT system integration.
 *
 * Usage: npx tsx scripts/bootstrap-system.ts <system-id> <display-name>
 * Example: npx tsx scripts/bootstrap-system.ts pf2e "Pathfinder 2e"
 *
 * Creates:
 *   src/lib/test-fixtures/{system}-character.ts  (fixture skeleton)
 *   src/lib/templates/systems/{system}.ts         (template skeleton)
 *
 * Then reminds you to:
 *   1. Fill in the fixture with real actor data
 *   2. Customize the template layout
 *   3. Add exports to index files
 *   4. Write tests
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';

const systemId = process.argv[2];
const displayName = process.argv[3];

if (!systemId || !displayName) {
  console.error('Usage: npx tsx scripts/bootstrap-system.ts <system-id> <display-name>');
  console.error('Example: npx tsx scripts/bootstrap-system.ts pf2e "Pathfinder 2e"');
  process.exit(1);
}

const safeName = systemId.replace(/[^a-z0-9]/gi, '-').toLowerCase();
const constName = `TEMPLATE_A4_${systemId.replace(/[^a-z0-9]/gi, '_').toUpperCase()}`;
const fixtureConst = `${systemId.replace(/[^a-z0-9]/gi, '_').toUpperCase()}_CHARACTER`;

// ── Fixture ──────────────────────────────────────────────────────────────────

const fixturePath = `src/lib/test-fixtures/${safeName}-character.ts`;
const fixtureContent = `/**
 * ${displayName} character actor data
 * Based on Foundry VTT ${systemId} system
 *
 * TODO: Fill in with real actor data from the system's data model.
 * See CLAUDE.md "Adding a New Foundry System" for the workflow.
 */

import type { ActorData } from '$lib/connectors/foundry';

export const ${fixtureConst}: ActorData = {
  id: 'TODO_ACTOR_ID',
  name: 'TODO Character Name',
  type: 'character',
  img: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==',
  system: {
    // TODO: Add system-specific fields from the data model
  },
  items: [
    // TODO: Add typical items for this system
  ],
  effects: [],
  flags: {},
  prototypeToken: {
    name: 'TODO',
    displayName: 20,
    actorLink: true,
    width: 1,
    height: 1,
    texture: {
      src: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==',
    },
    disposition: 1,
  },
  _meta: {
    systemId: '${systemId}',
    systemVersion: '1.0.0',
    foundryVersion: '13.0.0',
    exportedAt: new Date().toISOString(),
  },
};
`;

// ── Template ─────────────────────────────────────────────────────────────────

const templatePath = `src/lib/templates/systems/${safeName}.ts`;
const templateContent = `/**
 * ${displayName} Character Sheet — A4 Template
 * Composed from agnostic building blocks.
 *
 * TODO: Customize sections for this system's data model.
 */

import {
  BASE_STYLES,
  background,
  footer,
  header,
  itemList,
  section,
  statRow,
} from '../blocks';
import { registerTemplate } from '../definitions';
import type { TemplateDefinition } from '../types';

export const ${constName}: TemplateDefinition = {
  meta: {
    id: 'pdf-a4-${safeName}',
    name: '${displayName} Character Sheet',
    description: 'Character sheet for ${displayName}',
    systemId: '${systemId}',
    width: 210,
    height: 297,
    exports: ['pdf', 'png'],
  },
  styles: BASE_STYLES,
  layout: [
    ...background(210, 297),
    ...header(210, {
      subtitle1: '{{actor.type}}',
      badge: '${displayName}',
    }),

    // TODO: Add system-specific sections
    // Examples:
    // ...statRow([{ label: 'HP', binding: '{{actor.system.hp.value}}' }], 58),
    // ...itemList('FEATURES', 80, { filter: '{{item.system.type}}', filterValue: 'feat' }),

    ...itemList('ITEMS', 58, { maxItems: 25 }),
    ...footer('${displayName} — Generated by Sheet Magnet', 297),
  ],
};

registerTemplate(${constName});
`;

// ── Write files ──────────────────────────────────────────────────────────────

mkdirSync('src/lib/test-fixtures', { recursive: true });
mkdirSync('src/lib/templates/systems', { recursive: true });

if (existsSync(fixturePath)) {
  console.error(`SKIP  ${fixturePath} (already exists)`);
} else {
  writeFileSync(fixturePath, fixtureContent);
  console.log(`OK    ${fixturePath}`);
}

if (existsSync(templatePath)) {
  console.error(`SKIP  ${templatePath} (already exists)`);
} else {
  writeFileSync(templatePath, templateContent);
  console.log(`OK    ${templatePath}`);
}

console.log(`
Next steps:
  1. Fill in ${fixturePath} with real actor data
  2. Customize ${templatePath} with system-specific sections
  3. Add exports:
     - echo 'export { ${fixtureConst} } from "./${safeName}-character";' >> src/lib/test-fixtures/index.ts
     - echo 'export { ${constName} } from "./${safeName}";' >> src/lib/templates/systems/index.ts
  4. Add tests in pipeline.test.ts and e2e-pdf.test.ts
  5. Run: pnpm check && npx tsx scripts/generate-pdfs.ts
`);
